---
- hosts: update
  become: yes
  become_user: root
  tasks:
#AWS - Develop patching strategy for both RHEL and Amazon Linux
# As DevOps Engineer i want to ensure that all Linux systems are patched against the latest threats and have the latest bugfixes
        - name: patch RHEL or/and Amazon
          yum: name='*' state=latest
          when: ansible_distribution == "CentOS" or ansible_distribution == 'Amazon'

        - name: patch Ubuntu
          apt:
            name: '*'
            state: latest
#            autoremove: yes
#            autoclean: yes
#            upgrade: yes
          when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

#        - name: set a cron
#          cron: 
#           name: patch Ubuntu
#           minute: '30'
#           hour: '20'
#           day: '31'
#           month: '7'
#           weekday: '5'
#           job: /.*/PatchOS.yml

        - name: reboot OS after Patching
          reboot:
            reboot_timeout: 60
            msg: "Reboot system after Patching initiated by ansible" 
                

